apiVersion: v1
kind: Pod
metadata:
  name: web_app
spec:
  volumes:
    - name: mysql-data
      hostPath:
        path: ~/.local/share/containers/storage/volumes/db-data
        type: DirectoryOrCreate
  containers:
    - name: mysql-container
      image: debian-mysql
      volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      ports:
        - containerPort: 3306
          hostPort: 33006

    - name: nginx-container
      image: docker.io/library/nginx:latest
      ports:
        - containerPort: 80
          hostPort: 8080

