apiVersion: v1
kind: LimitRange
metadata:
  name: developer-limits
  namespace: developer-workspace
spec:
  limits:
    - type: Pod
      min:
        cpu: 200m
        memory: 512Mi
      max:
        cpu: "1"
        memory: 1024Mi
    - type: Container
      min:
        cpu: 100m
        memory: 256Mi
      max:
        cpu: "1"
        memory: 1024Mi

