apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: student-admin-binding
  namespace: student-workspace
subjects:
  - kind: User
    name: student
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: namespace-admin
  apiGroup: rbac.authorization.k8s.io

