pipeline {
    agent {
        docker {
            image 'jenkinsci/jnlp-agent-docker'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    tools {
        dockerTool 'docker-lab'
    }

    environment {
        REGISTRY_CREDENTIALS_ID = 'quay-io-creds'
    }

    parameters {
        string(name: 'VERSION', defaultValue: 'latest', description: 'Tag for the Docker image')
        string(name: 'MYSQL_ROOT_PASSWORD', defaultValue: 'rootpassword', description: 'Root password for MySQL')
        string(name: 'MYSQL_DATABASE', defaultValue: 'developer_db', description: 'Database name for MySQL')
        string(name: 'MYSQL_USER', defaultValue: 'developer', description: 'User name for MySQL')
        string(name: 'MYSQL_PASSWORD', defaultValue: 'developerpassword', description: 'User password for MySQL')
    }

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    sh """
                    docker build -t debian-mysql:${params.VERSION} \
                      --build-arg MYSQL_ROOT_PASSWORD=${params.MYSQL_ROOT_PASSWORD} \
                      --build-arg MYSQL_DATABASE=${params.MYSQL_DATABASE} \
                      --build-arg MYSQL_USER=${params.MYSQL_USER} \
                      --build-arg MYSQL_PASSWORD=${params.MYSQL_PASSWORD} \
                      ci-example/.
                    """
                }
            }
        }
        stage('Push Docker Image to Quay') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: "${env.REGISTRY_CREDENTIALS_ID}", usernameVariable: 'REGISTRY_USERNAME', passwordVariable: 'REGISTRY_PASSWORD')]) {
                        sh """
                        echo ${REGISTRY_PASSWORD} | docker login -u ${REGISTRY_USERNAME} --password-stdin quay.io
                        docker tag debian-mysql:${params.VERSION} quay.io/${REGISTRY_USERNAME}/debian-mysql:${params.VERSION}
                        docker push quay.io/${REGISTRY_USERNAME}/debian-mysql:${params.VERSION}
                        """
                    }
                }
            }
        }
    }
}