version: '3'

services:
  mysql:
    image: debian-mysql
    container_name: mysql-container
    environment:
      - MYSQL_DATABASE=nginx_db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "33006:3306"
    restart: unless-stopped

  nginx:
    image: docker.io/library/nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - mysql

volumes:
  mysql-data:

