apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        last-restart: "2024-06-19T12:00:00Z"
    spec:
      initContainers:
      - name: init-sleep
        image: busybox
        command: ['sh', '-c', 'echo "Sleeping for 20 seconds..."; sleep 20']
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        - name: config-volume
          mountPath: /etc/nginx/conf.d
        env:
        - name: DUMMY_SECRET
          valueFrom:
            secretKeyRef:
              name: nginx-secret
              key: dummyKey
      volumes:
      - name: html-volume
        persistentVolumeClaim:
          claimName: nginx-pvc
      - name: config-volume
        configMap:
          name: nginx-configmap

