apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: webapp
data:
  default.conf: |
    server {
      listen 8080;
      server_name localhost;

      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
    }

