apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: webapp
spec:
  storageClassName: vsphere-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

