apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-cnf-config
  namespace: student-workspace
data:
  mariadb.cnf: |
    [client-server]
    port = 33060
    socket = /var/run/mysqld/mysqld.sock
    
    !includedir /etc/mysql/conf.d/
    !includedir /etc/mysql/mariadb.conf.d/
    
    [mysqld]
    bind-address = 0.0.0.0
    pid-file=/var/run/mysqld/mysqld.pid
