apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: student-workspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      securityContext:
        runAsUser: 100
        fsGroup: 100
      containers:
        - name: mysql
          image: quay.io/pie3ro/debian-mysql:1.0.1-ocp
          ports:
            - containerPort: 33060
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1024Mi"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-env-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-env-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-env-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-env-secret
                  key: MYSQL_PASSWORD
          readinessProbe:
            exec:
              command:
                - /usr/bin/mysqladmin
                - ping
                - "-h"
                - "127.0.0.1"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - /usr/bin/mysqladmin
                - ping
                - "-h"
                - "127.0.0.1"
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: mariadb-cnf-volume
              mountPath: /etc/mysql/mariadb.cnf
              subPath: mariadb.cnf
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-cnf-volume
          configMap:
            name: mariadb-cnf-config
            items:
              - key: mariadb.cnf
                path: mariadb.cnf
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
      imagePullSecrets:
        - name: quayio-pull-secret

