apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mysql-hpa
  namespace: developer-workspace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mysql-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50

