apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: student-workspace
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 33060
      nodePort: 31036  #  nodePort w zakresie 30000-32767

